# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creat_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_task_creat(object):
    def setupUi(self, form_task_creat):
        form_task_creat.setObjectName("form_task_creat")
        form_task_creat.resize(276, 229)
        form_task_creat.setMinimumSize(QtCore.QSize(276, 229))
        form_task_creat.setMaximumSize(QtCore.QSize(276, 229))
        self.groupBox = QtWidgets.QGroupBox(form_task_creat)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 261, 201))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 131, 16))
        self.label_2.setObjectName("label_2")
        self.task = QtWidgets.QLineEdit(self.groupBox)
        self.task.setGeometry(QtCore.QRect(10, 40, 241, 21))
        self.task.setObjectName("task")
        self.pushbutton_creat = QtWidgets.QPushButton(self.groupBox)
        self.pushbutton_creat.setGeometry(QtCore.QRect(180, 160, 75, 23))
        self.pushbutton_creat.setObjectName("pushbuttton_creat")
        self.pushbutton_cancel = QtWidgets.QPushButton(self.groupBox)
        self.pushbutton_cancel.setGeometry(QtCore.QRect(180, 130, 75, 23))
        self.pushbutton_cancel.setObjectName("pyshbutton_cancel")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setGeometry(QtCore.QRect(10, 90, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")

        self.retranslateUi(form_task_creat)
        QtCore.QMetaObject.connectSlotsByName(form_task_creat)

    def retranslateUi(self, form_task_creat):
        _translate = QtCore.QCoreApplication.translate
        form_task_creat.setWindowTitle(_translate("form_task_creat", "Form"))
        self.groupBox.setTitle(_translate("form_task_creat", "Создать задачу"))
        self.label.setText(_translate("form_task_creat", "Введите описание задачи"))
        self.label_2.setText(_translate("form_task_creat", "Выберете дату и время"))
        self.pushbutton_creat.setText(_translate("form_task_creat", "Создать"))
        self.pushbutton_cancel.setText(_translate("form_task_creat", "Отмена"))
