# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 440)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 440))
        self.centralwidget.setMaximumSize(QtCore.QSize(500, 440))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.box_school = QtWidgets.QComboBox(self.groupBox)
        self.box_school.setObjectName("box_school")
        self.horizontalLayout.addWidget(self.box_school)
        self.box_class = QtWidgets.QComboBox(self.groupBox)
        self.box_class.setObjectName("box_class")
        self.horizontalLayout.addWidget(self.box_class)
        self.buttton_result = QtWidgets.QPushButton(self.groupBox)
        self.buttton_result.setObjectName("buttton_result")
        self.horizontalLayout.addWidget(self.buttton_result)
        self.verticalLayout.addWidget(self.groupBox)
        self.table = QtWidgets.QTableWidget(self.groupBox_2)
        self.table.setObjectName("table")
        self.verticalLayout.addWidget(self.table)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", ""))
        self.groupBox.setTitle(_translate("MainWindow", ""))
        self.buttton_result.setText(_translate("MainWindow", "Узнать результат"))
